# This workflow provided by GitHub Actions Manager
# Documentation: https://github.com/vemel/github_actions_js/blob/main/python_workflows/README.md
#
# - Starts on Pull Request opened or edited event
# - Pull Request notes must be in [Keep a Changelog](https://keepachangelog.com/en/1.0.0/) format
# - If Pull Request branch name is `release/*`, adds `release` label
# - If Pull Request notes has `Removed` section, adds `major` label
# - If Pull Request notes has `Added`, `Changed` or `Deprecated` sections, adds `minor` label
# - Otherwise adds `patch` label

name: Update Pull Request labels
"on":
  pull_request:
    types:
      - opened
      - edited
      - reopened
  workflow_dispatch:
    inputs:
      number:
        description: Pull Request number
        required: true
jobs:
  update-pull-request-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Get Pull Request
        uses: actions/github-script@v6
        id: pull-request
        with:
          script: |
            let pullRequest = null;
            if (context.payload.inputs && context.payload.inputs.number) {
              const number = context.payload.inputs.number;
              // find Pull Request by number fom input
              try {
                pullRequest = (await github.pulls.get({