# This workflow provided by GitHub Actions Manager
# Documentation: https://github.com/vemel/github_actions_js/blob/main/python_workflows/README.md
#
# --- How to modify this workflow and still get updates ---
# - Set 'github-actions-managed' to false on manual edit to prevent step overwrite on update
# - User-added steps survive update as well
# - Deleted steps are restored on update, so make them empty instead of removing
# - This comment is user-editable and is not updated automatically

name: Run style checks and unit tests
"on":
  push: {}
  workflow_dispatch: {}
jobs:
  check:
    runs-on: ubuntu-latest
    env:
      PIPENV_HIDE_EMOJIS: 1
      PIPENV_NOSPIN: 1
      PIPENV_IGNORE_VIRTUALENVS: 1
      PYTHONUSERBASE: ${{ github.workspace }}/.cache/py-user-base
    strategy:
      matrix:
        python-version:
          - 3.11
    steps:
      - name: Add PYTHONUSERBASE to PATH
        id: add-pythonuserbase
        run: |
          echo '${{ env.PYTHONUSERBASE }}/bin/' >> $GITHUB_PATH
      - name: Checkout current branch
        id: checkout
        uses: actions/checkout@v3
      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v3
        with:
          python-version: "${{ matrix.python-version }}"
      - name: Cache pip downloads