# This workflow provided by GitHub Actions Manager
# Documentation: https://github.com/vemel/github_actions_js/blob/main/python_workflows/README.md
#
# - Runs only if `PYPI_PASSWORD` secret is set
# - Starts on Pull Request merge for `release/*` branch
# - Uses Pull Request branch for deployment, so released version contains only changes
#   from base branch when Release had been published
# - Builds package if `build` script is available in `package.json`
# - Publishes new version to [PyPI](https://pypi.org/)

name: Publish to PyPI
"on":
  pull_request:
    types:
      - closed
  workflow_dispatch:
    inputs:
      number:
        description: Pull Request number
        required: true
jobs:
  publish-to-pypi:
    runs-on: ubuntu-latest
    env:
      PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
    steps:
      - name: Get Pull Request
        id: pull-request
        if: env.PYPI_PASSWORD
        uses: actions/github-script@v6
        with:
          script: |
            let pullRequest = null;
            if (context.payload.inputs && context.payload.inputs.number) {
              // find Pull Request by number fom input
              const number = context.payload.inputs.number;
              try {
                pullRequest = (await github.pulls.get({
                  owner: context.repo.owner,
                  repo: context.repo.repo,