# This workflow provided by GitHub Actions Manager
# Documentation: https://github.com/vemel/github_actions_js/blob/main/nodejs_workflows/README.md
#
# - Starts only manually
# - Can be used if you do not enforce Pull Request-based updates and commit directly to `target` branch
# - Creates or updates a release draft for `target` branch
# - Release notes are populated from `Unreleased` section of `CHANGELOG.md`
# - Sets suggested version as `name` and `tag` of the Release
# - Project-agnostic, can be used on any kind of project, change path: ./package.json to path to your version file

name: Create Release draft
"on":
  workflow_dispatch:
    inputs:
      release:
        description: "Release type: stable, rc, alpha, or beta"
        required: true
        default: stable
jobs:
  create-release-draft:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Release target branch
        id: checkout
        uses: actions/checkout@v3
      - name: Get Unreleased notes
        id: unreleased
        uses: vemel/nextchange@latest
        with:
          get: Unreleased
          sanitize: true
      - name: Get or create Release draft
        uses: actions/github-script@v6
        id: release