# This workflow provided by GitHub Actions Manager
# Documentation: https://github.com/vemel/github_actions_js/blob/main/nodejs_workflows/README.md
#
# - Starts on Pull Request merge for non-`release/*` branch
# - Creates or updates a Release draft for Pull Request base branch
# - Release draft notes are merged from existing notes and Pull Request notes
# - Each entry added from Pull Request notes contains a link to the Pull Request
# - Release draft suggested version is based on Release notes
# - Project-agnostic, can be used on any kind of project, change path: ./package.json to path to your version file
#
# Environment:
#   RELEASE_TYPE - Release suggested version: stable, rc, alpha, beta (default: `rc`)

name: Update Release from Pull Request
"on":
  pull_request:
    types:
      - closed
  workflow_dispatch:
    inputs:
      number:
        description: Pull Request number
        required: true
jobs:
  update-release-draft:
    runs-on: ubuntu-latest
    env:
      RELEASE_TYPE: rc
    steps:
      - name: Get Pull Request
        uses: actions/github-script@v6
        id: pull-request
        with:
          script: |
            let pullRequest = null;
            if (context.payload.inputs && context.payload.inputs.number) {
              const number = context.payload.inputs.number;
              // find Pull Request by number fom input
              try {
                pullRequest = (await github.pulls.get({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  pull_number: number,
                })).data;
              } catch(e) {
                core.error(`Cannot get Pull Request #${number}: ${e}`);
                return;
              }
            }
            if (context.payload.pull_request){
              // get Pull Request from event payload
              pullRequest = context.payload.pull_request;
            }

            if (!pullRequest) {
              core.error(`Cannot find Pull Request`);
              return;
            }

            // Stop if Pull request is not merged