# This workflow provided by GitHub Actions Manager
# Documentation: https://github.com/vemel/github_actions_js/blob/main/nodejs_workflows/README.md
#
# - Starts on Release published
# - Release notes must be in [Keep a Changelog](https://keepachangelog.com/en/1.0.0/) format
# - Creates a Release Pull Request from Release target branch with `release` label
# - If the release is not a prerelease, cleans up `Unreleased` section in `CHANGELOG.md`
# - Release Pull Request contains only version bump in `package.json` and updated `CHANGELOG.md`
# - Release Pull Request uses branch `release/<version>`
# - Signs commits if `GPG_PRIVATE_KEY` secret is set
#
# Secrets:
#   GPG_PRIVATE_KEY - Key to sign commits https://docs.github.com/en/github/authenticating-to-github/generating-a-new-gpg-key
#   GPG_PRIVATE_KEY_PASSPHRASE - Passphrase for GPG private key
